language: ruby
rvm:
  - "2.0.0"


  

script: bundle exec rspec spec

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
